/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import org.json.JSONObject;

/**
 *
 * @author marci
 */
public class Desbravador extends javax.swing.JPanel {

    private JSONObject dados;
    
    public Desbravador(JSONObject dados) {
        initComponents();
        this.dados = dados;
        
        nomeCompleto.setText(dados.optString("nomeCompleto", ""));
        email.setText(dados.optString("email", ""));
        cpf.setText(dados.optString("cpf", ""));
        rg.setText(dados.optString("rg", ""));
        dataNascimento.setText(dados.optString("dataNascimento", ""));
        nomeMae.setText(dados.optString("nomeMae", ""));
        nomePai.setText(dados.optString("nomePai", ""));

    }

    public Desbravador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCompleto = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        nomePai = new javax.swing.JLabel();
        nomeMae = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nomeCompletoLabel1 = new javax.swing.JLabel();
        dataNascimentoLabel = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        nomeMaeLabel = new javax.swing.JLabel();
        nomePaiLabel = new javax.swing.JLabel();
        editarBtn = new javax.swing.JButton();
        voltarBtn1 = new javax.swing.JButton();
        deletarBtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 51));
        setMinimumSize(new java.awt.Dimension(500, 600));

        nomeCompleto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nomeCompleto.setText("Nome Completo");

        email.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        email.setText("jLabel1");

        dataNascimento.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dataNascimento.setText("jLabel1");

        cpf.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cpf.setText("jLabel1");

        rg.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rg.setText("jLabel1");

        nomePai.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nomePai.setText("jLabel1");

        nomeMae.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nomeMae.setText("jLabel1");

        emailLabel.setText("Data Nasc");

        nomeCompletoLabel1.setText("Nome completo:");

        dataNascimentoLabel.setText("E-mail:");

        rgLabel.setText("RG:");

        cpfLabel.setText("CPF:");

        nomeMaeLabel.setText("Nome da mãe:");

        nomePaiLabel.setText("Nome do pai:");

        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        voltarBtn1.setText("Voltar");
        voltarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtn1ActionPerformed(evt);
            }
        });

        deletarBtn2.setText("Deletar");
        deletarBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtn2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/LençoD.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deletarBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(voltarBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(nomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCompletoLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nomePaiLabel)
                                                .addGap(6, 6, 6))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dataNascimentoLabel)
                                                .addComponent(emailLabel)
                                                .addComponent(rgLabel)
                                                .addComponent(cpfLabel)
                                                .addComponent(nomeMaeLabel)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nomePai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoLabel1)
                    .addComponent(nomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimentoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLabel)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(nomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeMaeLabel)
                    .addComponent(nomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePaiLabel)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(deletarBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltarBtn1)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtn1ActionPerformed
        // TODO add your handling code here:

        javax.swing.JFrame janela = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Cria o novo painel (Menu)
        view.ListaDesbravadores desbravadores = new view.ListaDesbravadores();

        // 3. Remove o painel atual e adiciona o novo
        janela.getContentPane().removeAll();
        janela.getContentPane().add(desbravadores);

        // 4. Atualiza a tela
        janela.revalidate();
        janela.repaint();
    }//GEN-LAST:event_voltarBtn1ActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JFrame janela = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Cria o novo painel (Menu)
        view.EditarDesbravador cadastrarDesbravador = new view.EditarDesbravador(dados);

        // 3. Remove o painel atual e adiciona o novo
        janela.getContentPane().removeAll();
        janela.getContentPane().add(cadastrarDesbravador);

        // 4. Atualiza a tela
        janela.revalidate();
        janela.repaint();
    }//GEN-LAST:event_editarBtnActionPerformed

    private void deletarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtn2ActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja deletar este usuário?",
        "Confirmação",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        
        String cpfUsuario = dados.getString("cpf");

        controller.DesbravadorController.deletarUsuario(cpfUsuario);

        // Volta para lista após deletar
        javax.swing.JFrame janela = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        view.ListaDesbravadores lista = new view.ListaDesbravadores();

        janela.getContentPane().removeAll();
        janela.getContentPane().add(lista);
        janela.revalidate();
        janela.repaint();
    }
    }//GEN-LAST:event_deletarBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel dataNascimento;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JButton deletarBtn2;
    private javax.swing.JButton editarBtn;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeCompleto;
    private javax.swing.JLabel nomeCompletoLabel1;
    private javax.swing.JLabel nomeMae;
    private javax.swing.JLabel nomeMaeLabel;
    private javax.swing.JLabel nomePai;
    private javax.swing.JLabel nomePaiLabel;
    private javax.swing.JLabel rg;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JButton voltarBtn1;
    // End of variables declaration//GEN-END:variables
}
