/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.DefaultListModel;
import org.json.JSONObject;
import org.json.JSONArray;
import controller.DesbravadorController;

public class ListaDesbravadores extends javax.swing.JPanel {

    private DefaultListModel modeloLista = new DefaultListModel(); //array ["", ""]

    private void pegarNomesDosDesbravadores() {

        JSONArray array = DesbravadorController.mostrarUsuarios();

        for (int i = 0; i < array.length(); i++) {
            JSONObject obj = array.getJSONObject(i);
            String nome = obj.getString("nomeCompleto");
            modeloLista.addElement(nome);
        }

    }

    public ListaDesbravadores() {
        initComponents();
        listaDesbravadores.setModel(modeloLista);
        pegarNomesDosDesbravadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaDesbravadores = new javax.swing.JList<>();

        listaDesbravadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaDesbravadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDesbravadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaDesbravadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaDesbravadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDesbravadoresMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {
            int index = listaDesbravadores.getSelectedIndex();

            if (index != 1) {
                JSONArray array = controller.DesbravadorController.mostrarUsuarios(); //JSONArray é equivalente de ArrayList
                JSONObject selecionado = array.getJSONObject(index); //JSONOBject == objeto 

                
                javax.swing.JFrame janela = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

                Desbravador telaDesbravador = new Desbravador(selecionado);
                janela.getContentPane().removeAll(); 
                janela.getContentPane().add(telaDesbravador);
                janela.pack();
                janela.setLocationRelativeTo(null);
                janela.revalidate();
                janela.repaint();
            }

        }
    }//GEN-LAST:event_listaDesbravadoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaDesbravadores;
    // End of variables declaration//GEN-END:variables
}
